// Package redfishapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// RedfishServer implements the ServerInterface for Redfish v1 API
type RedfishServer struct {
	// Add dependencies here (database, logger, etc.)
}

// NewRedfishServer creates a new instance of RedfishServer
func NewRedfishServer() *RedfishServer {
	return &RedfishServer{}
}

// GetServiceRoot implements ServerInterface method
func (r *RedfishServer) GetServiceRoot(c *gin.Context) {
	// Return a simplified JSON response to avoid struct complexity
	c.JSON(200, gin.H{
		"@odata.id":      "/redfish/v1/",
		"@odata.type":    "#ServiceRoot.v1_18_0.ServiceRoot",
		"Id":             "RootService",
		"Name":           "Root Service",
		"RedfishVersion": "1.18.0",
		"UUID":           "92384634-2938-2342-8820-489239905423",
		"Systems":        gin.H{"@odata.id": "/redfish/v1/Systems"},
		"Chassis":        gin.H{"@odata.id": "/redfish/v1/Chassis"},
		"Managers":       gin.H{"@odata.id": "/redfish/v1/Managers"},
	})
}

// GetChassisCollection implements ServerInterface method
func (r *RedfishServer) GetChassisCollection(c *gin.Context) {
	// Return a simplified JSON response
	c.JSON(200, gin.H{
		"@odata.id":           "/redfish/v1/Chassis",
		"@odata.type":         "#ChassisCollection.ChassisCollection",
		"Name":                "Chassis Collection",
		"Members":             []gin.H{{"@odata.id": "/redfish/v1/Chassis/1"}},
		"Members@odata.count": 1,
	})
}

// GetChassis implements ServerInterface method
func (r *RedfishServer) GetChassis(c *gin.Context, chassisId string) {
	// Return a simplified JSON response
	c.JSON(200, gin.H{
		"@odata.id":    "/redfish/v1/Chassis/" + chassisId,
		"@odata.type":  "#Chassis.v1_26_0.Chassis",
		"Id":           chassisId,
		"Name":         "Computer System Chassis",
		"ChassisType":  "Rack",
		"Manufacturer": "Example Manufacturer",
		"Model":        "Example Model",
		"SerialNumber": "2M220100SL",
	})
}

// GetManagersCollection implements ServerInterface method
func (r *RedfishServer) GetManagersCollection(c *gin.Context) {
	// Return a simplified JSON response
	c.JSON(200, gin.H{
		"@odata.id":           "/redfish/v1/Managers",
		"@odata.type":         "#ManagerCollection.ManagerCollection",
		"Name":                "Manager Collection",
		"Members":             []gin.H{{"@odata.id": "/redfish/v1/Managers/BMC"}},
		"Members@odata.count": 1,
	})
}

// GetManagersManagerId implements ServerInterface method
func (r *RedfishServer) GetManagersManagerId(c *gin.Context, managerId string) {
	// Return a simplified JSON response
	c.JSON(200, gin.H{
		"@odata.id":       "/redfish/v1/Managers/" + managerId,
		"@odata.type":     "#Manager.v1_22_0.Manager",
		"Id":              managerId,
		"Name":            "Manager",
		"ManagerType":     "BMC",
		"FirmwareVersion": "1.00",
		"Model":           "Example BMC",
	})
}

// GetSystemsCollection implements ServerInterface method
func (r *RedfishServer) GetSystemsCollection(c *gin.Context) {
	// Return a simplified JSON response
	c.JSON(200, gin.H{
		"@odata.id":           "/redfish/v1/Systems",
		"@odata.type":         "#ComputerSystemCollection.ComputerSystemCollection",
		"Name":                "Computer System Collection",
		"Members":             []gin.H{{"@odata.id": "/redfish/v1/Systems/1"}},
		"Members@odata.count": 1,
	})
}

// GetSystemsComputerSystemId implements ServerInterface method
func (r *RedfishServer) GetSystemsComputerSystemId(c *gin.Context, computerSystemId string) {
	// Return a simplified JSON response
	c.JSON(200, gin.H{
		"@odata.id":    "/redfish/v1/Systems/" + computerSystemId,
		"@odata.type":  "#ComputerSystem.v1_22_0.ComputerSystem",
		"Id":           computerSystemId,
		"Name":         "Computer System",
		"SystemType":   "Physical",
		"Manufacturer": "Example Manufacturer",
		"Model":        "Example System",
		"SerialNumber": "437XR1138R2",
		"PowerState":   "On",
	})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/", wrapper.GetServiceRoot)
	router.GET(options.BaseURL+"/Chassis", wrapper.GetChassisCollection)
	router.GET(options.BaseURL+"/Chassis/:chassisId", wrapper.GetChassis)
	router.GET(options.BaseURL+"/Managers", wrapper.GetManagersCollection)
	router.GET(options.BaseURL+"/Managers/:managerId", wrapper.GetManager)
	router.GET(options.BaseURL+"/Systems", wrapper.GetSystemsCollection)
	router.GET(options.BaseURL+"/Systems/:systemId", wrapper.GetSystem)
}

// Defines values for ActionInfoParameterTypes.
const (
	Boolean     ActionInfoParameterTypes = "Boolean"
	Number      ActionInfoParameterTypes = "Number"
	NumberArray ActionInfoParameterTypes = "NumberArray"
	Object      ActionInfoParameterTypes = "Object"
	ObjectArray ActionInfoParameterTypes = "ObjectArray"
	String      ActionInfoParameterTypes = "String"
	StringArray ActionInfoParameterTypes = "StringArray"
)

// Defines values for ChassisChassisType.
const (
	Blade            ChassisChassisType = "Blade"
	Card             ChassisChassisType = "Card"
	Cartridge        ChassisChassisType = "Cartridge"
	Component        ChassisChassisType = "Component"
	Drawer           ChassisChassisType = "Drawer"
	Enclosure        ChassisChassisType = "Enclosure"
	Expansion        ChassisChassisType = "Expansion"
	HeatExchanger    ChassisChassisType = "HeatExchanger"
	IPBasedDrive     ChassisChassisType = "IPBasedDrive"
	ImmersionTank    ChassisChassisType = "ImmersionTank"
	Module           ChassisChassisType = "Module"
	Other            ChassisChassisType = "Other"
	Pod              ChassisChassisType = "Pod"
	PowerStrip       ChassisChassisType = "PowerStrip"
	Rack             ChassisChassisType = "Rack"
	RackGroup        ChassisChassisType = "RackGroup"
	RackMount        ChassisChassisType = "RackMount"
	Row              ChassisChassisType = "Row"
	Shelf            ChassisChassisType = "Shelf"
	Sidecar          ChassisChassisType = "Sidecar"
	Sled             ChassisChassisType = "Sled"
	StandAlone       ChassisChassisType = "StandAlone"
	StorageEnclosure ChassisChassisType = "StorageEnclosure"
	Zone             ChassisChassisType = "Zone"
)

// Defines values for ComputerSystemSystemType.
const (
	Composed              ComputerSystemSystemType = "Composed"
	DPU                   ComputerSystemSystemType = "DPU"
	OS                    ComputerSystemSystemType = "OS"
	Physical              ComputerSystemSystemType = "Physical"
	PhysicallyPartitioned ComputerSystemSystemType = "PhysicallyPartitioned"
	Virtual               ComputerSystemSystemType = "Virtual"
	VirtuallyPartitioned  ComputerSystemSystemType = "VirtuallyPartitioned"
)

// Defines values for ManagerManagerType.
const (
	AuxiliaryController  ManagerManagerType = "AuxiliaryController"
	BMC                  ManagerManagerType = "BMC"
	EnclosureManager     ManagerManagerType = "EnclosureManager"
	FabricManager        ManagerManagerType = "FabricManager"
	ManagementController ManagerManagerType = "ManagementController"
	RackManager          ManagerManagerType = "RackManager"
	Service              ManagerManagerType = "Service"
)

// Defines values for ResolutionStepResolutionType.
const (
	CollectDiagnosticData ResolutionStepResolutionType = "CollectDiagnosticData"
	ContactVendor         ResolutionStepResolutionType = "ContactVendor"
	FirmwareUpdate        ResolutionStepResolutionType = "FirmwareUpdate"
	OEM                   ResolutionStepResolutionType = "OEM"
	PowerCycle            ResolutionStepResolutionType = "PowerCycle"
	ReplaceComponent      ResolutionStepResolutionType = "ReplaceComponent"
	Reset                 ResolutionStepResolutionType = "Reset"
	ResetToDefaults       ResolutionStepResolutionType = "ResetToDefaults"
)

// Defines values for ResourceConditionType.
const (
	Alert         ResourceConditionType = "Alert"
	Informational ResourceConditionType = "Informational"
	Subsystem     ResourceConditionType = "Subsystem"
)

// Defines values for ResourceHealth.
const (
	Critical ResourceHealth = "Critical"
	OK       ResourceHealth = "OK"
	Warning  ResourceHealth = "Warning"
)

// Defines values for ResourcePowerState.
const (
	Off         ResourcePowerState = "Off"
	On          ResourcePowerState = "On"
	Paused      ResourcePowerState = "Paused"
	PoweringOff ResourcePowerState = "PoweringOff"
	PoweringOn  ResourcePowerState = "PoweringOn"
)

// Defines values for ResourceState.
const (
	Absent             ResourceState = "Absent"
	Deferring          ResourceState = "Deferring"
	Degraded           ResourceState = "Degraded"
	Disabled           ResourceState = "Disabled"
	Enabled            ResourceState = "Enabled"
	InTest             ResourceState = "InTest"
	Qualified          ResourceState = "Qualified"
	Quiesced           ResourceState = "Quiesced"
	StandbyOffline     ResourceState = "StandbyOffline"
	StandbySpare       ResourceState = "StandbySpare"
	Starting           ResourceState = "Starting"
	UnavailableOffline ResourceState = "UnavailableOffline"
	Updating           ResourceState = "Updating"
)

// ActionInfoParameterTypes defines model for ActionInfo_ParameterTypes.
type ActionInfoParameterTypes string

// ActionInfoParameters The information about a parameter included in a Redfish action for this resource.
type ActionInfoParameters struct {
	// AllowableNumbers The allowable numeric values or duration values, inclusive ranges of values, and incremental step values for this parameter as applied to this action target.
	AllowableNumbers *[]string `json:"AllowableNumbers,omitempty"`

	// AllowablePattern The allowable pattern for this parameter as applied to this action target.
	AllowablePattern *string `json:"AllowablePattern"`

	// AllowableValueDescriptions Descriptions of allowable values for this parameter.
	AllowableValueDescriptions *[]string `json:"AllowableValueDescriptions,omitempty"`

	// AllowableValues The allowable values for this parameter as applied to this action target.
	AllowableValues *[]string `json:"AllowableValues,omitempty"`

	// ArraySizeMaximum The maximum number of array elements allowed for this parameter.
	ArraySizeMaximum *int64 `json:"ArraySizeMaximum"`

	// ArraySizeMinimum The minimum number of array elements required for this parameter.
	ArraySizeMinimum *int64 `json:"ArraySizeMinimum"`

	// DataType The JSON property type for this parameter.
	DataType *ActionInfoParameters_DataType `json:"DataType,omitempty"`

	// DefaultValue The default value for this parameter.
	DefaultValue *string `json:"DefaultValue"`

	// MaximumValue The maximum supported value for this parameter.
	MaximumValue *float32 `json:"MaximumValue"`

	// MinimumValue The minimum supported value for this parameter.
	MinimumValue *float32 `json:"MinimumValue"`

	// Name The name of the parameter for this action.
	Name *string `json:"Name,omitempty"`

	// NoDefaultValue Indicates that there is no default value for this parameter.
	NoDefaultValue *bool `json:"NoDefaultValue"`

	// ObjectDataType The data type of an object-based parameter.
	ObjectDataType *string `json:"ObjectDataType"`

	// Required An indication of whether the parameter is required to complete this action.
	Required *bool `json:"Required,omitempty"`
}

// ActionInfoParametersDataType1 defines model for .
type ActionInfoParametersDataType1 = interface{}

// ActionInfoParameters_DataType The JSON property type for this parameter.
type ActionInfoParameters_DataType struct {
	union json.RawMessage
}

// ChassisCollectionChassisCollection The collection of `Chassis` resource instances.
type ChassisCollectionChassisCollection struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataEtag The current ETag of the resource.
	OdataEtag *OdataV4Etag `json:"@odata.etag,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType   *OdataV4Type                                    `json:"@odata.type,omitempty"`
	Description *ChassisCollectionChassisCollection_Description `json:"Description,omitempty"`

	// Members The members of this collection.
	Members *[]OdataV4IdRef `json:"Members,omitempty"`

	// MembersOdataCount The number of items in a collection.
	MembersOdataCount *OdataV4Count `json:"Members@odata.count,omitempty"`

	// MembersOdataNextLink The URI to the resource containing the next set of partial members.
	MembersOdataNextLink *OdataV4NextLink `json:"Members@odata.nextLink,omitempty"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`
}

// ChassisCollectionChassisCollectionDescription1 defines model for .
type ChassisCollectionChassisCollectionDescription1 = interface{}

// ChassisCollectionChassisCollection_Description defines model for ChassisCollectionChassisCollection.Description.
type ChassisCollectionChassisCollection_Description struct {
	union json.RawMessage
}

// ChassisChassis The `Chassis` schema represents the physical components of a system.  This resource represents the sheet-metal confined spaces and logical zones such as racks, enclosures, chassis and all other containers.  Subsystems, such as sensors, that operate outside of a system's data plane are linked either directly or indirectly through this resource.  A subsystem that operates outside of a system's data plane are not accessible to software that runs on the system.  It also describes the location, such as a slot, socket, or bay, where a unit can be installed, by populating a resource instance with an absent state if a unit is not present.
type ChassisChassis struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataEtag The current ETag of the resource.
	OdataEtag *OdataV4Etag `json:"@odata.etag,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType   *OdataV4Type       `json:"@odata.type,omitempty"`
	ChassisType ChassisChassisType `json:"ChassisType"`

	// Id The unique identifier for this resource within the collection of similar resources.
	Id ResourceId `json:"Id"`

	// Manufacturer The manufacturer of this chassis.
	Manufacturer *string `json:"Manufacturer"`

	// Model The model number of the chassis.
	Model *string `json:"Model"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// SerialNumber The serial number of the chassis.
	SerialNumber *string `json:"SerialNumber"`

	// Status The status and health of a resource and its children.
	Status *ResourceStatus `json:"Status,omitempty"`
}

// ChassisChassisType defines model for Chassis_ChassisType.
type ChassisChassisType string

// ComputerSystemCollectionComputerSystemCollection The collection of `ComputerSystem` resource instances.
type ComputerSystemCollectionComputerSystemCollection struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataEtag The current ETag of the resource.
	OdataEtag *OdataV4Etag `json:"@odata.etag,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType   *OdataV4Type                                                  `json:"@odata.type,omitempty"`
	Description *ComputerSystemCollectionComputerSystemCollection_Description `json:"Description,omitempty"`

	// Members The members of this collection.
	Members *[]OdataV4IdRef `json:"Members,omitempty"`

	// MembersOdataCount The number of items in a collection.
	MembersOdataCount *OdataV4Count `json:"Members@odata.count,omitempty"`

	// MembersOdataNextLink The URI to the resource containing the next set of partial members.
	MembersOdataNextLink *OdataV4NextLink `json:"Members@odata.nextLink,omitempty"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`
}

// ComputerSystemCollectionComputerSystemCollectionDescription1 defines model for .
type ComputerSystemCollectionComputerSystemCollectionDescription1 = interface{}

// ComputerSystemCollectionComputerSystemCollection_Description defines model for ComputerSystemCollectionComputerSystemCollection.Description.
type ComputerSystemCollectionComputerSystemCollection_Description struct {
	union json.RawMessage
}

// ComputerSystemComputerSystem The `ComputerSystem` schema represents a computer or system instance and the software-visible resources, or items within the data plane, such as memory, CPU, and other devices that it can access.  Details of those resources or subsystems are also linked through this resource.
type ComputerSystemComputerSystem struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType   *OdataV4Type                              `json:"@odata.type,omitempty"`
	Description *ComputerSystemComputerSystem_Description `json:"Description,omitempty"`

	// Id The unique identifier for this resource within the collection of similar resources.
	Id ResourceId `json:"Id"`

	// Manufacturer The manufacturer or OEM of this system.
	Manufacturer *string `json:"Manufacturer"`

	// Model The product name for this system, without the manufacturer name.
	Model *string `json:"Model"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// PowerState The current power state of the system.
	PowerState *ComputerSystemComputerSystem_PowerState `json:"PowerState,omitempty"`

	// SerialNumber The serial number for this system.
	SerialNumber *string `json:"SerialNumber"`

	// Status The status and health of a resource and its children.
	Status     *ResourceStatus           `json:"Status,omitempty"`
	SystemType *ComputerSystemSystemType `json:"SystemType,omitempty"`
}

// ComputerSystemComputerSystemDescription1 defines model for .
type ComputerSystemComputerSystemDescription1 = interface{}

// ComputerSystemComputerSystem_Description defines model for ComputerSystemComputerSystem.Description.
type ComputerSystemComputerSystem_Description struct {
	union json.RawMessage
}

// ComputerSystemComputerSystemPowerState1 defines model for .
type ComputerSystemComputerSystemPowerState1 = interface{}

// ComputerSystemComputerSystem_PowerState The current power state of the system.
type ComputerSystemComputerSystem_PowerState struct {
	union json.RawMessage
}

// ComputerSystemSystemType defines model for ComputerSystem_SystemType.
type ComputerSystemSystemType string

// ManagerCollectionManagerCollection The collection of `Manager` resource instances.
type ManagerCollectionManagerCollection struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataEtag The current ETag of the resource.
	OdataEtag *OdataV4Etag `json:"@odata.etag,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType   *OdataV4Type                                    `json:"@odata.type,omitempty"`
	Description *ManagerCollectionManagerCollection_Description `json:"Description,omitempty"`

	// Members The members of this collection.
	Members *[]OdataV4IdRef `json:"Members,omitempty"`

	// MembersOdataCount The number of items in a collection.
	MembersOdataCount *OdataV4Count `json:"Members@odata.count,omitempty"`

	// MembersOdataNextLink The URI to the resource containing the next set of partial members.
	MembersOdataNextLink *OdataV4NextLink `json:"Members@odata.nextLink,omitempty"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`
}

// ManagerCollectionManagerCollectionDescription1 defines model for .
type ManagerCollectionManagerCollectionDescription1 = interface{}

// ManagerCollectionManagerCollection_Description defines model for ManagerCollectionManagerCollection.Description.
type ManagerCollectionManagerCollection_Description struct {
	union json.RawMessage
}

// ManagerManager In Redfish, a manager is a systems management entity that can implement or provide access to a Redfish service.  Examples of managers are BMCs (baseboard management controllers), enclosure managers, management controllers, and other subsystems that are assigned manageability functions.  An implementation can have multiple managers, which might be directly accessible through a Redfish-defined interface.
type ManagerManager struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataEtag The current ETag of the resource.
	OdataEtag *OdataV4Etag `json:"@odata.etag,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType   *OdataV4Type                `json:"@odata.type,omitempty"`
	Description *ManagerManager_Description `json:"Description,omitempty"`

	// FirmwareVersion The firmware version of this manager.
	FirmwareVersion *string `json:"FirmwareVersion"`

	// Id The unique identifier for this resource within the collection of similar resources.
	Id          ResourceId          `json:"Id"`
	ManagerType *ManagerManagerType `json:"ManagerType,omitempty"`

	// Model The model information of this manager, as defined by the manufacturer.
	Model *string `json:"Model"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`

	// Status The status and health of a resource and its children.
	Status *ResourceStatus `json:"Status,omitempty"`
}

// ManagerManagerDescription1 defines model for .
type ManagerManagerDescription1 = interface{}

// ManagerManager_Description defines model for ManagerManager.Description.
type ManagerManager_Description struct {
	union json.RawMessage
}

// ManagerManagerType defines model for Manager_ManagerType.
type ManagerManagerType string

// MessageMessage The message that the Redfish service returns.
type MessageMessage struct {
	// Message The human-readable message.
	Message *string `json:"Message,omitempty"`

	// MessageArgs An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.
	MessageArgs *[]string `json:"MessageArgs,omitempty"`

	// MessageId The identifier for the message.
	MessageId       *string         `json:"MessageId,omitempty"`
	MessageSeverity *ResourceHealth `json:"MessageSeverity,omitempty"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`

	// RelatedProperties A set of properties described by the message.
	RelatedProperties *[]string `json:"RelatedProperties,omitempty"`

	// Resolution Used to provide suggestions on how to resolve the situation that caused the message.
	Resolution *string `json:"Resolution,omitempty"`

	// ResolutionSteps The list of recommended steps to resolve the situation that caused the message.
	ResolutionSteps *[]ResolutionStepResolutionStep `json:"ResolutionSteps,omitempty"`

	// Severity The severity of the message.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Severity *string `json:"Severity,omitempty"`
}

// RedfishError The error payload from a Redfish service.
type RedfishError struct {
	// Error The properties that describe an error from a Redfish service.
	Error struct {
		// MessageExtendedInfo An array of messages describing one or more error messages.
		MessageExtendedInfo *[]MessageMessage `json:"@Message.ExtendedInfo,omitempty"`

		// Code A string indicating a specific `MessageId` from a message registry.
		Code *string `json:"code,omitempty"`

		// Message A human-readable error message corresponding to the message in a message registry.
		Message *string `json:"message,omitempty"`
	} `json:"error"`
}

// ResolutionStepResolutionStep This type describes a recommended step of the service-defined resolution.
type ResolutionStepResolutionStep struct {
	// ActionParameters The parameters of the action URI for a resolution step.
	ActionParameters *[]ResolutionStepResolutionStep_ActionParameters_Item `json:"ActionParameters,omitempty"`

	// ActionURI The action URI for a resolution step.
	ActionURI *string `json:"ActionURI,omitempty"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`

	// Priority The priority in the set of resolution steps.
	Priority *int64 `json:"Priority"`

	// ResolutionType The type of the resolution step.
	ResolutionType *ResolutionStepResolutionStep_ResolutionType `json:"ResolutionType,omitempty"`

	// RetryCount The number of retries for a resolution step.
	RetryCount *int64 `json:"RetryCount"`

	// RetryIntervalSeconds The interval between retries for a resolution step.
	RetryIntervalSeconds *int64 `json:"RetryIntervalSeconds"`

	// TargetComponentURI The target URI of the component for a resolution step.
	TargetComponentURI *string `json:"TargetComponentURI"`
}

// ResolutionStepResolutionStepActionParameters1 defines model for .
type ResolutionStepResolutionStepActionParameters1 = interface{}

// ResolutionStepResolutionStep_ActionParameters_Item defines model for ResolutionStep_ResolutionStep.ActionParameters.Item.
type ResolutionStepResolutionStep_ActionParameters_Item struct {
	union json.RawMessage
}

// ResolutionStepResolutionStepResolutionType1 defines model for .
type ResolutionStepResolutionStepResolutionType1 = interface{}

// ResolutionStepResolutionStep_ResolutionType The type of the resolution step.
type ResolutionStepResolutionStep_ResolutionType struct {
	union json.RawMessage
}

// ResolutionStepResolutionType defines model for ResolutionStep_ResolutionType.
type ResolutionStepResolutionType string

// ResourceCondition A condition that requires attention.
type ResourceCondition struct {
	// ConditionType The type of condition.
	ConditionType *ResourceCondition_ConditionType `json:"ConditionType,omitempty"`

	// LogEntry A reference to a resource.
	LogEntry *OdataV4IdRef `json:"LogEntry,omitempty"`

	// Message The human-readable message for this condition.
	Message *string `json:"Message,omitempty"`

	// MessageArgs An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.
	MessageArgs *[]string `json:"MessageArgs,omitempty"`

	// MessageId The identifier for the message.
	MessageId *string `json:"MessageId,omitempty"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`

	// OriginOfCondition A reference to a resource.
	OriginOfCondition *OdataV4IdRef `json:"OriginOfCondition,omitempty"`

	// Resolution Suggestions on how to resolve the condition.
	Resolution *string `json:"Resolution,omitempty"`

	// ResolutionSteps The list of recommended steps to resolve the condition.
	ResolutionSteps *[]ResolutionStepResolutionStep `json:"ResolutionSteps,omitempty"`
	Severity        *ResourceHealth                 `json:"Severity,omitempty"`

	// Timestamp The time the condition occurred.
	Timestamp *time.Time `json:"Timestamp,omitempty"`

	// UserAuthenticationSource The source of authentication for the username property associated with the condition.
	UserAuthenticationSource *string `json:"UserAuthenticationSource"`

	// Username The username of the account associated with the condition.
	Username *string `json:"Username"`
}

// ResourceConditionConditionType1 defines model for .
type ResourceConditionConditionType1 = interface{}

// ResourceCondition_ConditionType The type of condition.
type ResourceCondition_ConditionType struct {
	union json.RawMessage
}

// ResourceConditionType defines model for Resource_ConditionType.
type ResourceConditionType string

// ResourceDescription The description of this resource.  Used for commonality in the schema definitions.
type ResourceDescription = string

// ResourceHealth defines model for Resource_Health.
type ResourceHealth string

// ResourceId The unique identifier for this resource within the collection of similar resources.
type ResourceId = string

// ResourceName The name of the resource or array member.
type ResourceName = string

// ResourceOem The OEM extension.
type ResourceOem map[string]interface{}

// ResourcePowerState defines model for Resource_PowerState.
type ResourcePowerState string

// ResourceState defines model for Resource_State.
type ResourceState string

// ResourceStatus The status and health of a resource and its children.
type ResourceStatus struct {
	// Conditions Conditions in this resource that require attention.
	Conditions *[]ResourceStatus_Conditions_Item `json:"Conditions,omitempty"`

	// Health The health state of this resource in the absence of its dependent resources.
	Health *ResourceStatus_Health `json:"Health,omitempty"`

	// HealthRollup The overall health state from the view of this resource.
	HealthRollup *ResourceStatus_HealthRollup `json:"HealthRollup,omitempty"`

	// Oem The OEM extension.
	Oem *ResourceOem `json:"Oem,omitempty"`

	// State The state of the resource.
	State *ResourceStatus_State `json:"State,omitempty"`
}

// ResourceStatusConditions1 defines model for .
type ResourceStatusConditions1 = interface{}

// ResourceStatus_Conditions_Item defines model for Resource_Status.Conditions.Item.
type ResourceStatus_Conditions_Item struct {
	union json.RawMessage
}

// ResourceStatusHealth1 defines model for .
type ResourceStatusHealth1 = interface{}

// ResourceStatus_Health The health state of this resource in the absence of its dependent resources.
type ResourceStatus_Health struct {
	union json.RawMessage
}

// ResourceStatusHealthRollup1 defines model for .
type ResourceStatusHealthRollup1 = interface{}

// ResourceStatus_HealthRollup The overall health state from the view of this resource.
type ResourceStatus_HealthRollup struct {
	union json.RawMessage
}

// ResourceStatusState1 defines model for .
type ResourceStatusState1 = interface{}

// ResourceStatus_State The state of the resource.
type ResourceStatus_State struct {
	union json.RawMessage
}

// ServiceRootServiceRoot The `ServiceRoot` schema describes the root of the Redfish service, located at the '/redfish/v1' URI.  All other resources accessible through the Redfish interface on this device are linked directly or indirectly from the service root.
type ServiceRootServiceRoot struct {
	// OdataContext The OData description of a payload.
	OdataContext *OdataV4Context `json:"@odata.context,omitempty"`

	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`

	// OdataType The type of a resource.
	OdataType *OdataV4Type `json:"@odata.type,omitempty"`

	// Chassis A reference to a resource.
	Chassis     *OdataV4IdRef                       `json:"Chassis,omitempty"`
	Description *ServiceRootServiceRoot_Description `json:"Description,omitempty"`

	// Id The unique identifier for this resource within the collection of similar resources.
	Id ResourceId `json:"Id"`

	// Managers A reference to a resource.
	Managers *OdataV4IdRef `json:"Managers,omitempty"`

	// Name The name of the resource or array member.
	Name ResourceName `json:"Name"`

	// RedfishVersion The version of the Redfish service.
	RedfishVersion *string `json:"RedfishVersion,omitempty"`

	// Systems A reference to a resource.
	Systems *OdataV4IdRef `json:"Systems,omitempty"`

	// UUID Unique identifier for a service instance.  When SSDP is used, this value contains the same UUID returned in an HTTP `200 OK` response from an SSDP `M-SEARCH` request during discovery.
	UUID *string `json:"UUID"`
}

// ServiceRootServiceRootDescription1 defines model for .
type ServiceRootServiceRootDescription1 = interface{}

// ServiceRootServiceRoot_Description defines model for ServiceRootServiceRoot.Description.
type ServiceRootServiceRoot_Description struct {
	union json.RawMessage
}

// OdataV4Context The OData description of a payload.
type OdataV4Context = string

// OdataV4Count The number of items in a collection.
type OdataV4Count = int64

// OdataV4Etag The current ETag of the resource.
type OdataV4Etag = string

// OdataV4Id The unique identifier for a resource.
type OdataV4Id = string

// OdataV4IdRef A reference to a resource.
type OdataV4IdRef struct {
	// OdataId The unique identifier for a resource.
	OdataId *OdataV4Id `json:"@odata.id,omitempty"`
}

// OdataV4NextLink The URI to the resource containing the next set of partial members.
type OdataV4NextLink = string

// OdataV4Type The type of a resource.
type OdataV4Type = string

// AsActionInfoParameterTypes returns the union data inside the ActionInfoParameters_DataType as a ActionInfoParameterTypes
func (t ActionInfoParameters_DataType) AsActionInfoParameterTypes() (ActionInfoParameterTypes, error) {
	var body ActionInfoParameterTypes
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionInfoParameterTypes overwrites any union data inside the ActionInfoParameters_DataType as the provided ActionInfoParameterTypes
func (t *ActionInfoParameters_DataType) FromActionInfoParameterTypes(v ActionInfoParameterTypes) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionInfoParameterTypes performs a merge with any union data inside the ActionInfoParameters_DataType, using the provided ActionInfoParameterTypes
func (t *ActionInfoParameters_DataType) MergeActionInfoParameterTypes(v ActionInfoParameterTypes) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionInfoParametersDataType1 returns the union data inside the ActionInfoParameters_DataType as a ActionInfoParametersDataType1
func (t ActionInfoParameters_DataType) AsActionInfoParametersDataType1() (ActionInfoParametersDataType1, error) {
	var body ActionInfoParametersDataType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionInfoParametersDataType1 overwrites any union data inside the ActionInfoParameters_DataType as the provided ActionInfoParametersDataType1
func (t *ActionInfoParameters_DataType) FromActionInfoParametersDataType1(v ActionInfoParametersDataType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionInfoParametersDataType1 performs a merge with any union data inside the ActionInfoParameters_DataType, using the provided ActionInfoParametersDataType1
func (t *ActionInfoParameters_DataType) MergeActionInfoParametersDataType1(v ActionInfoParametersDataType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionInfoParameters_DataType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionInfoParameters_DataType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceDescription returns the union data inside the ChassisCollectionChassisCollection_Description as a ResourceDescription
func (t ChassisCollectionChassisCollection_Description) AsResourceDescription() (ResourceDescription, error) {
	var body ResourceDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceDescription overwrites any union data inside the ChassisCollectionChassisCollection_Description as the provided ResourceDescription
func (t *ChassisCollectionChassisCollection_Description) FromResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceDescription performs a merge with any union data inside the ChassisCollectionChassisCollection_Description, using the provided ResourceDescription
func (t *ChassisCollectionChassisCollection_Description) MergeResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChassisCollectionChassisCollectionDescription1 returns the union data inside the ChassisCollectionChassisCollection_Description as a ChassisCollectionChassisCollectionDescription1
func (t ChassisCollectionChassisCollection_Description) AsChassisCollectionChassisCollectionDescription1() (ChassisCollectionChassisCollectionDescription1, error) {
	var body ChassisCollectionChassisCollectionDescription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChassisCollectionChassisCollectionDescription1 overwrites any union data inside the ChassisCollectionChassisCollection_Description as the provided ChassisCollectionChassisCollectionDescription1
func (t *ChassisCollectionChassisCollection_Description) FromChassisCollectionChassisCollectionDescription1(v ChassisCollectionChassisCollectionDescription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChassisCollectionChassisCollectionDescription1 performs a merge with any union data inside the ChassisCollectionChassisCollection_Description, using the provided ChassisCollectionChassisCollectionDescription1
func (t *ChassisCollectionChassisCollection_Description) MergeChassisCollectionChassisCollectionDescription1(v ChassisCollectionChassisCollectionDescription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChassisCollectionChassisCollection_Description) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChassisCollectionChassisCollection_Description) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceDescription returns the union data inside the ComputerSystemCollectionComputerSystemCollection_Description as a ResourceDescription
func (t ComputerSystemCollectionComputerSystemCollection_Description) AsResourceDescription() (ResourceDescription, error) {
	var body ResourceDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceDescription overwrites any union data inside the ComputerSystemCollectionComputerSystemCollection_Description as the provided ResourceDescription
func (t *ComputerSystemCollectionComputerSystemCollection_Description) FromResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceDescription performs a merge with any union data inside the ComputerSystemCollectionComputerSystemCollection_Description, using the provided ResourceDescription
func (t *ComputerSystemCollectionComputerSystemCollection_Description) MergeResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsComputerSystemCollectionComputerSystemCollectionDescription1 returns the union data inside the ComputerSystemCollectionComputerSystemCollection_Description as a ComputerSystemCollectionComputerSystemCollectionDescription1
func (t ComputerSystemCollectionComputerSystemCollection_Description) AsComputerSystemCollectionComputerSystemCollectionDescription1() (ComputerSystemCollectionComputerSystemCollectionDescription1, error) {
	var body ComputerSystemCollectionComputerSystemCollectionDescription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComputerSystemCollectionComputerSystemCollectionDescription1 overwrites any union data inside the ComputerSystemCollectionComputerSystemCollection_Description as the provided ComputerSystemCollectionComputerSystemCollectionDescription1
func (t *ComputerSystemCollectionComputerSystemCollection_Description) FromComputerSystemCollectionComputerSystemCollectionDescription1(v ComputerSystemCollectionComputerSystemCollectionDescription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComputerSystemCollectionComputerSystemCollectionDescription1 performs a merge with any union data inside the ComputerSystemCollectionComputerSystemCollection_Description, using the provided ComputerSystemCollectionComputerSystemCollectionDescription1
func (t *ComputerSystemCollectionComputerSystemCollection_Description) MergeComputerSystemCollectionComputerSystemCollectionDescription1(v ComputerSystemCollectionComputerSystemCollectionDescription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ComputerSystemCollectionComputerSystemCollection_Description) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComputerSystemCollectionComputerSystemCollection_Description) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceDescription returns the union data inside the ComputerSystemComputerSystem_Description as a ResourceDescription
func (t ComputerSystemComputerSystem_Description) AsResourceDescription() (ResourceDescription, error) {
	var body ResourceDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceDescription overwrites any union data inside the ComputerSystemComputerSystem_Description as the provided ResourceDescription
func (t *ComputerSystemComputerSystem_Description) FromResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceDescription performs a merge with any union data inside the ComputerSystemComputerSystem_Description, using the provided ResourceDescription
func (t *ComputerSystemComputerSystem_Description) MergeResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsComputerSystemComputerSystemDescription1 returns the union data inside the ComputerSystemComputerSystem_Description as a ComputerSystemComputerSystemDescription1
func (t ComputerSystemComputerSystem_Description) AsComputerSystemComputerSystemDescription1() (ComputerSystemComputerSystemDescription1, error) {
	var body ComputerSystemComputerSystemDescription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComputerSystemComputerSystemDescription1 overwrites any union data inside the ComputerSystemComputerSystem_Description as the provided ComputerSystemComputerSystemDescription1
func (t *ComputerSystemComputerSystem_Description) FromComputerSystemComputerSystemDescription1(v ComputerSystemComputerSystemDescription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComputerSystemComputerSystemDescription1 performs a merge with any union data inside the ComputerSystemComputerSystem_Description, using the provided ComputerSystemComputerSystemDescription1
func (t *ComputerSystemComputerSystem_Description) MergeComputerSystemComputerSystemDescription1(v ComputerSystemComputerSystemDescription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ComputerSystemComputerSystem_Description) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComputerSystemComputerSystem_Description) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourcePowerState returns the union data inside the ComputerSystemComputerSystem_PowerState as a ResourcePowerState
func (t ComputerSystemComputerSystem_PowerState) AsResourcePowerState() (ResourcePowerState, error) {
	var body ResourcePowerState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourcePowerState overwrites any union data inside the ComputerSystemComputerSystem_PowerState as the provided ResourcePowerState
func (t *ComputerSystemComputerSystem_PowerState) FromResourcePowerState(v ResourcePowerState) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourcePowerState performs a merge with any union data inside the ComputerSystemComputerSystem_PowerState, using the provided ResourcePowerState
func (t *ComputerSystemComputerSystem_PowerState) MergeResourcePowerState(v ResourcePowerState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsComputerSystemComputerSystemPowerState1 returns the union data inside the ComputerSystemComputerSystem_PowerState as a ComputerSystemComputerSystemPowerState1
func (t ComputerSystemComputerSystem_PowerState) AsComputerSystemComputerSystemPowerState1() (ComputerSystemComputerSystemPowerState1, error) {
	var body ComputerSystemComputerSystemPowerState1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComputerSystemComputerSystemPowerState1 overwrites any union data inside the ComputerSystemComputerSystem_PowerState as the provided ComputerSystemComputerSystemPowerState1
func (t *ComputerSystemComputerSystem_PowerState) FromComputerSystemComputerSystemPowerState1(v ComputerSystemComputerSystemPowerState1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComputerSystemComputerSystemPowerState1 performs a merge with any union data inside the ComputerSystemComputerSystem_PowerState, using the provided ComputerSystemComputerSystemPowerState1
func (t *ComputerSystemComputerSystem_PowerState) MergeComputerSystemComputerSystemPowerState1(v ComputerSystemComputerSystemPowerState1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ComputerSystemComputerSystem_PowerState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComputerSystemComputerSystem_PowerState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceDescription returns the union data inside the ManagerCollectionManagerCollection_Description as a ResourceDescription
func (t ManagerCollectionManagerCollection_Description) AsResourceDescription() (ResourceDescription, error) {
	var body ResourceDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceDescription overwrites any union data inside the ManagerCollectionManagerCollection_Description as the provided ResourceDescription
func (t *ManagerCollectionManagerCollection_Description) FromResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceDescription performs a merge with any union data inside the ManagerCollectionManagerCollection_Description, using the provided ResourceDescription
func (t *ManagerCollectionManagerCollection_Description) MergeResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsManagerCollectionManagerCollectionDescription1 returns the union data inside the ManagerCollectionManagerCollection_Description as a ManagerCollectionManagerCollectionDescription1
func (t ManagerCollectionManagerCollection_Description) AsManagerCollectionManagerCollectionDescription1() (ManagerCollectionManagerCollectionDescription1, error) {
	var body ManagerCollectionManagerCollectionDescription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromManagerCollectionManagerCollectionDescription1 overwrites any union data inside the ManagerCollectionManagerCollection_Description as the provided ManagerCollectionManagerCollectionDescription1
func (t *ManagerCollectionManagerCollection_Description) FromManagerCollectionManagerCollectionDescription1(v ManagerCollectionManagerCollectionDescription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeManagerCollectionManagerCollectionDescription1 performs a merge with any union data inside the ManagerCollectionManagerCollection_Description, using the provided ManagerCollectionManagerCollectionDescription1
func (t *ManagerCollectionManagerCollection_Description) MergeManagerCollectionManagerCollectionDescription1(v ManagerCollectionManagerCollectionDescription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ManagerCollectionManagerCollection_Description) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ManagerCollectionManagerCollection_Description) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceDescription returns the union data inside the ManagerManager_Description as a ResourceDescription
func (t ManagerManager_Description) AsResourceDescription() (ResourceDescription, error) {
	var body ResourceDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceDescription overwrites any union data inside the ManagerManager_Description as the provided ResourceDescription
func (t *ManagerManager_Description) FromResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceDescription performs a merge with any union data inside the ManagerManager_Description, using the provided ResourceDescription
func (t *ManagerManager_Description) MergeResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsManagerManagerDescription1 returns the union data inside the ManagerManager_Description as a ManagerManagerDescription1
func (t ManagerManager_Description) AsManagerManagerDescription1() (ManagerManagerDescription1, error) {
	var body ManagerManagerDescription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromManagerManagerDescription1 overwrites any union data inside the ManagerManager_Description as the provided ManagerManagerDescription1
func (t *ManagerManager_Description) FromManagerManagerDescription1(v ManagerManagerDescription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeManagerManagerDescription1 performs a merge with any union data inside the ManagerManager_Description, using the provided ManagerManagerDescription1
func (t *ManagerManager_Description) MergeManagerManagerDescription1(v ManagerManagerDescription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ManagerManager_Description) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ManagerManager_Description) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsActionInfoParameters returns the union data inside the ResolutionStepResolutionStep_ActionParameters_Item as a ActionInfoParameters
func (t ResolutionStepResolutionStep_ActionParameters_Item) AsActionInfoParameters() (ActionInfoParameters, error) {
	var body ActionInfoParameters
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionInfoParameters overwrites any union data inside the ResolutionStepResolutionStep_ActionParameters_Item as the provided ActionInfoParameters
func (t *ResolutionStepResolutionStep_ActionParameters_Item) FromActionInfoParameters(v ActionInfoParameters) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionInfoParameters performs a merge with any union data inside the ResolutionStepResolutionStep_ActionParameters_Item, using the provided ActionInfoParameters
func (t *ResolutionStepResolutionStep_ActionParameters_Item) MergeActionInfoParameters(v ActionInfoParameters) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResolutionStepResolutionStepActionParameters1 returns the union data inside the ResolutionStepResolutionStep_ActionParameters_Item as a ResolutionStepResolutionStepActionParameters1
func (t ResolutionStepResolutionStep_ActionParameters_Item) AsResolutionStepResolutionStepActionParameters1() (ResolutionStepResolutionStepActionParameters1, error) {
	var body ResolutionStepResolutionStepActionParameters1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResolutionStepResolutionStepActionParameters1 overwrites any union data inside the ResolutionStepResolutionStep_ActionParameters_Item as the provided ResolutionStepResolutionStepActionParameters1
func (t *ResolutionStepResolutionStep_ActionParameters_Item) FromResolutionStepResolutionStepActionParameters1(v ResolutionStepResolutionStepActionParameters1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResolutionStepResolutionStepActionParameters1 performs a merge with any union data inside the ResolutionStepResolutionStep_ActionParameters_Item, using the provided ResolutionStepResolutionStepActionParameters1
func (t *ResolutionStepResolutionStep_ActionParameters_Item) MergeResolutionStepResolutionStepActionParameters1(v ResolutionStepResolutionStepActionParameters1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResolutionStepResolutionStep_ActionParameters_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResolutionStepResolutionStep_ActionParameters_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResolutionStepResolutionType returns the union data inside the ResolutionStepResolutionStep_ResolutionType as a ResolutionStepResolutionType
func (t ResolutionStepResolutionStep_ResolutionType) AsResolutionStepResolutionType() (ResolutionStepResolutionType, error) {
	var body ResolutionStepResolutionType
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResolutionStepResolutionType overwrites any union data inside the ResolutionStepResolutionStep_ResolutionType as the provided ResolutionStepResolutionType
func (t *ResolutionStepResolutionStep_ResolutionType) FromResolutionStepResolutionType(v ResolutionStepResolutionType) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResolutionStepResolutionType performs a merge with any union data inside the ResolutionStepResolutionStep_ResolutionType, using the provided ResolutionStepResolutionType
func (t *ResolutionStepResolutionStep_ResolutionType) MergeResolutionStepResolutionType(v ResolutionStepResolutionType) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResolutionStepResolutionStepResolutionType1 returns the union data inside the ResolutionStepResolutionStep_ResolutionType as a ResolutionStepResolutionStepResolutionType1
func (t ResolutionStepResolutionStep_ResolutionType) AsResolutionStepResolutionStepResolutionType1() (ResolutionStepResolutionStepResolutionType1, error) {
	var body ResolutionStepResolutionStepResolutionType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResolutionStepResolutionStepResolutionType1 overwrites any union data inside the ResolutionStepResolutionStep_ResolutionType as the provided ResolutionStepResolutionStepResolutionType1
func (t *ResolutionStepResolutionStep_ResolutionType) FromResolutionStepResolutionStepResolutionType1(v ResolutionStepResolutionStepResolutionType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResolutionStepResolutionStepResolutionType1 performs a merge with any union data inside the ResolutionStepResolutionStep_ResolutionType, using the provided ResolutionStepResolutionStepResolutionType1
func (t *ResolutionStepResolutionStep_ResolutionType) MergeResolutionStepResolutionStepResolutionType1(v ResolutionStepResolutionStepResolutionType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResolutionStepResolutionStep_ResolutionType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResolutionStepResolutionStep_ResolutionType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceConditionType returns the union data inside the ResourceCondition_ConditionType as a ResourceConditionType
func (t ResourceCondition_ConditionType) AsResourceConditionType() (ResourceConditionType, error) {
	var body ResourceConditionType
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceConditionType overwrites any union data inside the ResourceCondition_ConditionType as the provided ResourceConditionType
func (t *ResourceCondition_ConditionType) FromResourceConditionType(v ResourceConditionType) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceConditionType performs a merge with any union data inside the ResourceCondition_ConditionType, using the provided ResourceConditionType
func (t *ResourceCondition_ConditionType) MergeResourceConditionType(v ResourceConditionType) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceConditionConditionType1 returns the union data inside the ResourceCondition_ConditionType as a ResourceConditionConditionType1
func (t ResourceCondition_ConditionType) AsResourceConditionConditionType1() (ResourceConditionConditionType1, error) {
	var body ResourceConditionConditionType1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceConditionConditionType1 overwrites any union data inside the ResourceCondition_ConditionType as the provided ResourceConditionConditionType1
func (t *ResourceCondition_ConditionType) FromResourceConditionConditionType1(v ResourceConditionConditionType1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceConditionConditionType1 performs a merge with any union data inside the ResourceCondition_ConditionType, using the provided ResourceConditionConditionType1
func (t *ResourceCondition_ConditionType) MergeResourceConditionConditionType1(v ResourceConditionConditionType1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResourceCondition_ConditionType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResourceCondition_ConditionType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceCondition returns the union data inside the ResourceStatus_Conditions_Item as a ResourceCondition
func (t ResourceStatus_Conditions_Item) AsResourceCondition() (ResourceCondition, error) {
	var body ResourceCondition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceCondition overwrites any union data inside the ResourceStatus_Conditions_Item as the provided ResourceCondition
func (t *ResourceStatus_Conditions_Item) FromResourceCondition(v ResourceCondition) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceCondition performs a merge with any union data inside the ResourceStatus_Conditions_Item, using the provided ResourceCondition
func (t *ResourceStatus_Conditions_Item) MergeResourceCondition(v ResourceCondition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceStatusConditions1 returns the union data inside the ResourceStatus_Conditions_Item as a ResourceStatusConditions1
func (t ResourceStatus_Conditions_Item) AsResourceStatusConditions1() (ResourceStatusConditions1, error) {
	var body ResourceStatusConditions1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceStatusConditions1 overwrites any union data inside the ResourceStatus_Conditions_Item as the provided ResourceStatusConditions1
func (t *ResourceStatus_Conditions_Item) FromResourceStatusConditions1(v ResourceStatusConditions1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceStatusConditions1 performs a merge with any union data inside the ResourceStatus_Conditions_Item, using the provided ResourceStatusConditions1
func (t *ResourceStatus_Conditions_Item) MergeResourceStatusConditions1(v ResourceStatusConditions1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResourceStatus_Conditions_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResourceStatus_Conditions_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceHealth returns the union data inside the ResourceStatus_Health as a ResourceHealth
func (t ResourceStatus_Health) AsResourceHealth() (ResourceHealth, error) {
	var body ResourceHealth
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceHealth overwrites any union data inside the ResourceStatus_Health as the provided ResourceHealth
func (t *ResourceStatus_Health) FromResourceHealth(v ResourceHealth) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceHealth performs a merge with any union data inside the ResourceStatus_Health, using the provided ResourceHealth
func (t *ResourceStatus_Health) MergeResourceHealth(v ResourceHealth) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceStatusHealth1 returns the union data inside the ResourceStatus_Health as a ResourceStatusHealth1
func (t ResourceStatus_Health) AsResourceStatusHealth1() (ResourceStatusHealth1, error) {
	var body ResourceStatusHealth1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceStatusHealth1 overwrites any union data inside the ResourceStatus_Health as the provided ResourceStatusHealth1
func (t *ResourceStatus_Health) FromResourceStatusHealth1(v ResourceStatusHealth1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceStatusHealth1 performs a merge with any union data inside the ResourceStatus_Health, using the provided ResourceStatusHealth1
func (t *ResourceStatus_Health) MergeResourceStatusHealth1(v ResourceStatusHealth1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResourceStatus_Health) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResourceStatus_Health) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceHealth returns the union data inside the ResourceStatus_HealthRollup as a ResourceHealth
func (t ResourceStatus_HealthRollup) AsResourceHealth() (ResourceHealth, error) {
	var body ResourceHealth
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceHealth overwrites any union data inside the ResourceStatus_HealthRollup as the provided ResourceHealth
func (t *ResourceStatus_HealthRollup) FromResourceHealth(v ResourceHealth) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceHealth performs a merge with any union data inside the ResourceStatus_HealthRollup, using the provided ResourceHealth
func (t *ResourceStatus_HealthRollup) MergeResourceHealth(v ResourceHealth) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceStatusHealthRollup1 returns the union data inside the ResourceStatus_HealthRollup as a ResourceStatusHealthRollup1
func (t ResourceStatus_HealthRollup) AsResourceStatusHealthRollup1() (ResourceStatusHealthRollup1, error) {
	var body ResourceStatusHealthRollup1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceStatusHealthRollup1 overwrites any union data inside the ResourceStatus_HealthRollup as the provided ResourceStatusHealthRollup1
func (t *ResourceStatus_HealthRollup) FromResourceStatusHealthRollup1(v ResourceStatusHealthRollup1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceStatusHealthRollup1 performs a merge with any union data inside the ResourceStatus_HealthRollup, using the provided ResourceStatusHealthRollup1
func (t *ResourceStatus_HealthRollup) MergeResourceStatusHealthRollup1(v ResourceStatusHealthRollup1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResourceStatus_HealthRollup) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResourceStatus_HealthRollup) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceState returns the union data inside the ResourceStatus_State as a ResourceState
func (t ResourceStatus_State) AsResourceState() (ResourceState, error) {
	var body ResourceState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceState overwrites any union data inside the ResourceStatus_State as the provided ResourceState
func (t *ResourceStatus_State) FromResourceState(v ResourceState) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceState performs a merge with any union data inside the ResourceStatus_State, using the provided ResourceState
func (t *ResourceStatus_State) MergeResourceState(v ResourceState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceStatusState1 returns the union data inside the ResourceStatus_State as a ResourceStatusState1
func (t ResourceStatus_State) AsResourceStatusState1() (ResourceStatusState1, error) {
	var body ResourceStatusState1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceStatusState1 overwrites any union data inside the ResourceStatus_State as the provided ResourceStatusState1
func (t *ResourceStatus_State) FromResourceStatusState1(v ResourceStatusState1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceStatusState1 performs a merge with any union data inside the ResourceStatus_State, using the provided ResourceStatusState1
func (t *ResourceStatus_State) MergeResourceStatusState1(v ResourceStatusState1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResourceStatus_State) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResourceStatus_State) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResourceDescription returns the union data inside the ServiceRootServiceRoot_Description as a ResourceDescription
func (t ServiceRootServiceRoot_Description) AsResourceDescription() (ResourceDescription, error) {
	var body ResourceDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceDescription overwrites any union data inside the ServiceRootServiceRoot_Description as the provided ResourceDescription
func (t *ServiceRootServiceRoot_Description) FromResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceDescription performs a merge with any union data inside the ServiceRootServiceRoot_Description, using the provided ResourceDescription
func (t *ServiceRootServiceRoot_Description) MergeResourceDescription(v ResourceDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServiceRootServiceRootDescription1 returns the union data inside the ServiceRootServiceRoot_Description as a ServiceRootServiceRootDescription1
func (t ServiceRootServiceRoot_Description) AsServiceRootServiceRootDescription1() (ServiceRootServiceRootDescription1, error) {
	var body ServiceRootServiceRootDescription1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServiceRootServiceRootDescription1 overwrites any union data inside the ServiceRootServiceRoot_Description as the provided ServiceRootServiceRootDescription1
func (t *ServiceRootServiceRoot_Description) FromServiceRootServiceRootDescription1(v ServiceRootServiceRootDescription1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServiceRootServiceRootDescription1 performs a merge with any union data inside the ServiceRootServiceRoot_Description, using the provided ServiceRootServiceRootDescription1
func (t *ServiceRootServiceRoot_Description) MergeServiceRootServiceRootDescription1(v ServiceRootServiceRootDescription1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServiceRootServiceRoot_Description) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServiceRootServiceRoot_Description) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	GetServiceRoot(c *gin.Context)

	// (GET /Chassis)
	GetChassisCollection(c *gin.Context)

	// (GET /Chassis/{ChassisId})
	GetChassis(c *gin.Context, chassisId string)

	// (GET /Managers)
	GetManagersCollection(c *gin.Context)

	// (GET /Managers/{ManagerId})
	GetManagersManagerId(c *gin.Context, managerId string)

	// (GET /Systems)
	GetSystemsCollection(c *gin.Context)

	// (GET /Systems/{ComputerSystemId})
	GetSystemsComputerSystemId(c *gin.Context, computerSystemId string)
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

const (
	BasicAuthScopes  = "BasicAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// GetServiceRoot operation middleware
func (siw *ServerInterfaceWrapper) GetServiceRoot(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceRoot(c)
}

// GetMetadata handles the OData $metadata endpoint
func (siw *ServerInterfaceWrapper) GetMetadata(c *gin.Context) {
	c.Set(BasicAuthScopes, []string{})
	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	// Return OData metadata as XML
	metadataXML := `<?xml version="1.0" encoding="UTF-8"?>
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:DataServices>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Service">
            <EntityContainer Name="Service">
                <EntitySet Name="ServiceRoot" EntityType="ServiceRoot.ServiceRoot"/>
                <EntitySet Name="Systems" EntityType="ComputerSystemCollection.ComputerSystemCollection"/>
                <EntitySet Name="Chassis" EntityType="ChassisCollection.ChassisCollection"/>
                <EntitySet Name="Managers" EntityType="ManagerCollection.ManagerCollection"/>
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>`

	c.Header("Content-Type", "application/xml")
	c.String(200, metadataXML)
}

// GetChassisCollection operation middleware
func (siw *ServerInterfaceWrapper) GetChassisCollection(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChassisCollection(c)
}

// GetChassis operation middleware
func (siw *ServerInterfaceWrapper) GetChassis(c *gin.Context) {

	var err error

	// ------------- Path parameter "chassisId" -------------
	var chassisId string

	err = runtime.BindStyledParameterWithOptions("simple", "chassisId", c.Param("chassisId"), &chassisId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter chassisId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChassis(c, chassisId)
}

// GetManagersCollection operation middleware
func (siw *ServerInterfaceWrapper) GetManagersCollection(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetManagersCollection(c)
}

// GetManager operation middleware
func (siw *ServerInterfaceWrapper) GetManager(c *gin.Context) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", c.Param("managerId"), &managerId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter managerId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetManagersManagerId(c, managerId)
}

// / GetSystemsCollection operation middleware
func (siw *ServerInterfaceWrapper) GetSystemsCollection(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemsCollection(c)
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(c *gin.Context) {

	var err error

	// ------------- Path parameter "systemId" -------------
	var systemId string

	err = runtime.BindStyledParameterWithOptions("simple", "systemId", c.Param("systemId"), &systemId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter systemId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemsComputerSystemId(c, systemId)
}

// RegisterHandlers adds each server route to the Gin router.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers with Gin router, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router gin.IRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/redfish/v1/", wrapper.GetServiceRoot)
	router.GET(baseURL+"/redfish/v1/$metadata", wrapper.GetMetadata)
	router.GET(baseURL+"/redfish/v1/Chassis", wrapper.GetChassisCollection)
	router.GET(baseURL+"/redfish/v1/Chassis/:chassisId", wrapper.GetChassis)
	router.GET(baseURL+"/redfish/v1/Managers", wrapper.GetManagersCollection)
	router.GET(baseURL+"/redfish/v1/Managers/:managerId", wrapper.GetManager)
	router.GET(baseURL+"/redfish/v1/Systems", wrapper.GetSystemsCollection)
	router.GET(baseURL+"/redfish/v1/Systems/:systemId", wrapper.GetSystem)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3cbN7LgX8HpzTmZ2UvRlpOZnejLjiLbd7QzjrSSlbtnkowIdoMkrrsBBkBTZjz6",
	"73tQBaDRL7JJU/Ij/iSquwEUqgr1QqHwLkllsZSCCaOTk3eJThesoPDzNDVcinMxk7eXVNGCGaZer5cM",
	"XjJRFsnJT8n3UuaMimSU/FAWU6bCj1Ol6DoZJddGcTEPP/zji+l/s9SEH/j4l1Fi1kuWnCTat3p7ZEd6",
	"znSq+NLCA6P7UU+SUzLF3+MKBPtUwM9xA5yT5FQQan8SOXPf6HEFDrxnxZRlGcvI/7m++IFIeDNuQFrv",
	"KPoQenNztnDgRMaN+deb4zd6nNzfjzqxDnOmWcbtK5pfKrlkynBLiRnNNRslWYWg5CR5vWCEi5lUBbVP",
	"CJ3K0hBKlr5DwkWal3aOXBBKrlg243pBKIxNZlIRs+CaKKZlqVJmwV9Gg75LTvNc3tFpzhC78KwNA/Vf",
	"WVQzxVOyonnJNJGKZKVC4PDRCEHSfMWIomJuP5qFd1RYSFPFCiYMzYk2bOn7CtBWs6Oa0OUy5ywjRuJL",
	"NzVD1ZwBNblhBYAtyjy3MCYnRpWsyYH3o0Qxml2IfN34gDpOfnuUSzF/3pi8hQcxtiZ6QfOccJHxlBpG",
	"zAbMPCoaRvaLjM24QEawgH0dKBt37FYKAOAJp78maU5LzSyEtqnnouslS/nMzpVLMSbkpVTI63rkIKwj",
	"RrGlYpoJ08BMND6j6cKtl4LBwiakC8dS5GsyZcR36GAHBAe8APsheeOHZkEN0QD7mtAwzTGQeMWU5lKc",
	"WrmQnCSr49tvbp9a5gjouqTGMCW2LYQlfrYv1zaZtYc3I/E5jDlTKQwFWaDYvMypIuytRaKG4S1mcFJT",
	"pvuptOt8PjhrtJhgKLF/tOM3lVKd7PFbu0IGYOyDiCVPeYvgbA+YLbYbLbFjulwyqrxc0bRgXuOpDLnD",
	"Pp/UcaonAb6d2WMQ9G126SH5t10k36rnPg+d9PGtaSCFfXDNf2Ov6FteWPOzixYFvnQqC/gAOmI5aE2N",
	"I7KsZ/2h0ZScJFyYP387XOJyYdgczN99Ft5WoEEEA7SaqRVPGdHlcimV6V2T7QGFNC3dKMURjrRdBj5z",
	"CyJQgYsNVMCX/RNS7NeSq4+NDIOhnq7r1HhkIjynhr6GGXchH9yRMK7FTA+WpWAXs+Tkp3fJV4rNkpPk",
	"fzypvMEnzhV80u8H3o+CI2jp88v9L23C7EOHgROwiGAzWuYGhHM3MjL8AsVLDx4e2qoyA+AgHK3oNOeW",
	"MTLJNDDLUskVz1BC78hcfEYmV45jJx4YTSZ2UpMxIeczMvGcNKlG9FBP0GOdjFCBe7njZ7ZiCkU4zshI",
	"QgW5enn2l2d/+u7IexVAycoH7mLpPyFLO6G+gZJeSDrJx7JD0FT4qEUvTZ1IIcENGiLIHU56pfbOerLe",
	"8S6Gb4/E6ZjWVulz7EiFYnITqZwg/ahJ5WA8PKlqHX9YUv1Aix4SCWuQO8+9EkKBQGjV2d4fQhh2D74p",
	"KAXS/ge5Wd6fO3M22EtMMcKtVDukGpiGkOceZvauYCHzsbe0WOZsZEV6qZkC/FGRkSXV+k6qLA5kUMWI",
	"XGKoEGU3nWom0jbGdYAMgEkVy5gwnObYSalZdgBNY/nWfhDTbkKgT2i9RTFg2HWzxZNRQ9FOsDabcLHY",
	"oynVLHscVe/DI4Bgi0RvuIAmhMCtZevJX6WFdWxA5aKV68i+Xb1PWd1sjuh4x82C0DoeJog5wP8kCl5P",
	"MJDYK3Ka3UrLsFXXGpaip3abHqfCc5Wds5yRuwWDHhqLPbKmjSTW7swZLJEh0uc91uB7gHMPnref+E8o",
	"XatNC+n3NHYViYeO1b89cmHGy1rQ/l9/+Ike/XZ69M/bX9yPp0ff3f7yP//4v//6B2DLf7vO//2KaU3n",
	"7I8//zzubvJV1zpsT7AKp65ozjMCo1h+9LMIwZ7k3iL3bEG15vpM5jmD+d22nuyxFZKGxrAsXJeTgDLC",
	"hTZUpEy3NzrcerWUYm+NfbLJVYKPj1bf3vrv70e+B2bofHBz+Lhqy7PBLXkWtTNOYA5qCR+DSxXh791A",
	"H/HKofI2br3dPbTGJNuwgYTWkkbFxXVEyVq4bCBmrtjsAQKnNNrJy7l4ozEythn4auKBwUqxC3vZr1ud",
	"CPbW/IOLN4P7CQ0iU3EQmeFjq5xZMbiN/bYpQT31u9ERL4A6U492l71htTdtdlq96pMUQUCAvK2EMLda",
	"Ajbjqq2iT1v0eoG7h5it0IWkr1CMof7lYq15SnNSMQmYa0SvtWGFN3oCMRrN9YIxc1QwAz0IjC/oJbVU",
	"sfZMLufQ+29SME10aV0uTRRN3+gRYSLNpS4V0yOSIpjQCHaGwBxwy9m6VIRcl1MESo9CT5oJLRV4gNQQ",
	"iw9rTcjSaJ6xeCJfazSWljkVDAxpKxZYRhhHS4orlpp8DXaxCP+ZhZLlfNHQ5oScEu2hqQ2th41tDTya",
	"pkxrPs0hTKPlzNzZV9CbKoUm0m3SeEKcG0JzLRubfrlEo67CCSU6l2ZEtEzfMDOyM5rS9cjaWIoRSkrB",
	"DUmpsCYmrKE8Z9mITNdkKZdlTg0X83j9+XXm7FmBnosh2lhc85nvkvvYWHAgfu9a26291wPaNlb6a9fD",
	"eTZYkp9nGLET5YymplRM9UXsqi8qNYjDPlbcNQ41SDWngv+GhrZieikFrgpwe5TMytQyJIRhHZROKNVa",
	"FhR2kiNPb6ZkQe4WsojbgotbKvsfMH3pAkyOeQWzi5Iqbte+KhkaBTJjeQ8y7atoayKG8jFxOV2TuwVP",
	"Fy4sGVF4zgRTNM/XRLEZpFTIOpT7WhnXTHGa++yuLuRo+OLDYYfWMHFEc5CVLPMQgajlEF2ZcSdOY7Rc",
	"G2pKPRgx7vOmNRWv6E2203l2YAPKc7xUTpsGXR8U72bLCVSOXVegduKu91Q6bo3GSqfE8OzEIo9VeQag",
	"axyDTxCx0csqlnUKqmjyORl5Xlv4ZM4rmr5JRsn3Oc0sm7zwtIPsRSqy01wK+4/97pWz0M+oyvCPUTyb",
	"w2t5l4ySS2mfv3i7pELbGYySa56xlKpklPwT+7nOmf3mesHyWTJKnit6BwH+VzIrc/vBmV8Dlmkvv7eC",
	"9LniKw/DfypZLgE4qeicxfCeFwUGFF9TYef0N0bNi7fpggrcHr6Ud0xdG8Vt+wvLsztknwJ+MFcUhmQZ",
	"pJSxgh/5ByNi1ku7AvI1WVkWgZ9HUnEmjH3tLDq/ckBAFKXGaFxezucQ8DHSipYyN/yo2UCSWSnQVxFS",
	"Fbb7safHSXJKcik1IxmDzQypSMpVWnJDppIq6JqJDINd8TrBIJMbKyznsIrHNVJDgmsBjMjy2ZE3oTPf",
	"vjHIgGmNa0Sv+nevRySlKoMl7yYGeAuLFB96L21JLd4hm60yoaUKeBtXPDecmAup+G92vO3kdIavtitz",
	"y5wr1rVzBkXKU2KYKtxcah2HrdoZN4SKtQ/RVnw6ri0922etA2ZfZU4N0SWd8pxbKQZ8Qpc0tUYNhNKd",
	"c1RBWl9ItucFgx7do3FzqcaDA3Nl9jHEvolVmFKhtX9+6eL1gpk7qd5Yqgp0xmHg+orGOLN/RFIpczDd",
	"qHgzriRIYKCYgooVcmWNgVGstyxjvTc3oSBpobtNLzBQdLw7AHO0MhNa1+IQVsMvra5EbxaxmFM1ZyOS",
	"8zcMDEgq9FIq4+blndlxXdTZvpf2X9iTX8ZYWeY0rdKAf2NKHt2ge43+pR167OSuWy41sOK+KDn+7oiL",
	"dEHurH86U4xZvy6zFLLaeVyT38Dx9pcdCGcIWAMOoURzMc+DpW2X5sI6r1zMFNVGlWByjWtaCcgOzZpS",
	"M2OazzFw4JKULbyWwIVtaQHEkF59cmOn1bbSZhzU2YNIlEMoCK+FW1xaQFChYHYhO9CcG14TArZjlB+E",
	"G90rPsZev29DxEPMk2hecLtSodnU6mvcFosEWWTRVPwyAmY9CtyKY9kFVRSQQZyilqTEwDICRaTfGLms",
	"d92wR9oCGKevicZPx94oQs2NkayMrzhIN+udSuVZjkaRtJq68XIL0LTMWRBgFukYzgqKye/7uZ4sytiS",
	"KuuzgEOCls+PtU3Zdy3hvzq+ffbN7dO2yHc5022pXbWoiSX7+E/wOJYLLg23E6Gr49s/3z4FF8gaDKVh",
	"6hrmGG8e9bw4wB5SrecvW0lftpK+bCV92UratJXUEBi/hx2l2pQbwniv/aUGDtvbTBT2luw3lc6rNhWs",
	"yQLbHG4D5Miq12nOAtE0eJYgC+KoULWjUgWhClZItR6Rs8sbTKfxLhhqXIz3oQuIuy9jQp4zQ3nuVrF1",
	"zsO4AG3Yc4J9GwiEuY2j7q2hh1Mwn7OSePBtDkUuXrwKktptqT1KCDrKZG3snbY3YsJm35ZdB9wVMRj6",
	"D8lG3iy2i0SWpj2G/fxR0u0W8q49erz9UNGAkNfe53JpvIgw7ranN8x020T31XnOBqamJ68xLZWyesX7",
	"7LDjXCffaNcVE435UOc3NoC7x25OgxaPtdnVBUR9Hvvt2YwS1F+DtmrrKjRq2LR+HnOzB4CqvGMfM+o+",
	"//0ZWTB1uvlNk0vnQiej5EeuTAm/Lq6thxuc60uqDJg6sN/hPms+hri3hp/PL282bUcsFYPdRQvGxbWf",
	"LEqzBdVkypggWfjMEmhGVxJEf6CkJSCmklSkdBm/sBV24d81fdwoPtDcGQlTwECZM8V8wEYKjNfh+bkp",
	"xxBL4LRpLiH2J+eQoDt2eOjqCnTckqmZVAVKbx8CcilFaLIpCXkvLuoY7yBeF1SZH87PxkgriFE1kREM",
	"x3FEyy5wxr20hvA4VRlYmyEbHV8joB1deS6yjVf4mxQ0XXARJcioUgigoGjKxk7uivuytqa3gIfBFOj9",
	"j7qwaNN8Uq2RSfB77NtJLQAfGewuvNvBI5BUkXFN53PF5sDIlcFcmcSV4AEBqnEi7hRPzEQt2J5f3gwE",
	"q85vcjbLJc0cnlzatt6L69pAXVz3wSTIxbUl3mK9tJPTUpEVZ3dtg6DGq60B/NueYWxXnmUJtRKznqYX",
	"z6eggs7BWwXNqazLqzavhl5wap/uyy1SwFZnIVWUbliFPpFlKJlxVcD8LDbryzPim3gdtsB2L/sBjRgH",
	"TxCUbmukb0mPCbnClCSmiV7IMs9q9sjkEhlLquuyKKhaT8DvnLwCTzQ8q1xCyPXz9vHSN4ZG6L1Gy6lK",
	"WHERpwaUGwVLH3IOTlIPVJuiDYEWqNgbyY6kVogyo6BYHd8e/xmPHtWadqjd1fHts2MXhH4Fa0FF0efW",
	"k/cPO7suv8Sbv8Sbv8Sbv8SbN8Sbg6T4HQSa3Vy9wN1RzJ4L3+8omDRwHpAGPRPZOf5op8/vCWgkmEIM",
	"tRow4oubzx5mr5IIeYGHeWF1ueEw5Pv9qzNN/mA1GOZodZpX+o/RaYbQftTzcRybjgLMAD4aeC4fApvj",
	"Tv668qbGhJyKBq/AvBd0xaqN5goMTA0u+HwB+8vhdEN8BCFobYebo6oGnWFqRh80tv1FmXUrs5fOJnbW",
	"TrdSC4azO60dFIRjgMeKzbXgiAoZQmmeRpTWR++o1jLlYOcGiPfcE7CNh4TwGsLJn7bYmugfnwluYHm0",
	"ZbqPRYX2seUh0fgY8Y+juA+VXv+IMdZImlfJhr8XBd6MsL4KyDgLmi3OmfV6f5R8/+rMJwKGZ6flW55z",
	"qta1xteojpNR8pJOFU/994OTwLu6xdig/9dFjdAmqBkRVbByc2ppyIr028oUSoMYjMdABmgcOLSz3w+E",
	"2MluRP+sCXDms9/eCHnnYl3fvzrbaqv8sWHt4PEnLGfgusgYlmWAwIMFo5q9z/dbSG2CXYZz4WIOrWvJ",
	"h0ZWBomHvYtN9qVSyEFvkmVUo1Uzks4VsUgbaNyhweXqvVQ405FpisabD4riOVap0gXTBs+Fds6Bpkrq",
	"KDcQ4HG5rnF2f305dOOKF3hsrZCCG4kFdXFQjB+6SLqPJwfUzKBvQo2h6YJlRMjMwa/vuLEzgNztruV+",
	"EECqwxDVoomFxb6ccbeQOXRbLU7IGn4sWlbmt4/Ntj0E6Hqwh4GlgF3ms5eVkCbbGWgbgKoNsbgmy62O",
	"b589w7zPMLKvyAqBA9BSt+7vHlG1AluGckxNJ40oZkolOmJq0ZjtbhdlQcWRtbSgoKkb5SFqaNHesSr8",
	"nKq57qzOE0I+Hg1UzcuozKi1q60aMtyUJlTojD/zFdRc+7sFEySX8g3LSLlsvlVszrVR61rY66GrGdMP",
	"N004yrhw5Y2h7LFmBRWGpzoUPY5IFJ01bOyj+6+uXM8+4Q0rN8LRHanwFDMoxAlU58QoPO4FV4cXMYth",
	"aylHf1pVEuqLYwerNHJFWLheoWK386x7UYRDr5UX9qALYxLgmXTWtw+vXfWtYVXso4lesxVT3KwHexN/",
	"YzQ3iz09lyuWW+uobtE3ljTRDLROtPXj86Mq/7DC+QdZhFcvz/783dPjemHQpYSITyhD5w/fD5gIlMKj",
	"S/ulsg59m7kAeVrmpekMZ9xotDl9zE6X8znTLoVAoCcrwUXLV3jWX3NT4iJw0b8SunhYhrbdqzANz6R+",
	"QEKchtQQlFMMTnE1GzWWQFNi+eJxYP37c1Fxey5CmyVd55JmuoHea8OWPfsgOdcG805SWRR4HFTbz/dC",
	"76B9kzpct/V/LeAH5OsDTGtohcVYc3ghhMX9qv+ilRPK+F78fbKlnHQs0rJomxNZuCs/D79vsuMg/q8G",
	"uGJUdyB7WwZTCwc+6mx8ZQVXSt5tZjG4AQTvLAlrwYuLCUrndjkAXwpgvHf6YCeOOnUSDjX0PpXeJY9K",
	"f+Bqx49hzUNF/5S68kAQ2euILa3a2+Ch0Gxra8ybBLuEw+CAXqusxkBT3eHVK4vPNiXRPX6hlOxJnmX2",
	"lRfUmEPR3oVqOTasv8M4oyS+CQZCBzDY0EH+6rA2fvEWCwOci5kc5KME2mLOWxWtQgD8V4NVRNOH3F8p",
	"IB5azoa7DWwo2PejJJUZ6zTu0A6PTCRaaenI2vVU6PK7Dm9mvz9U96Ok6POmT5v+bQ1fDb8n5Czgy5rY",
	"eFgkHBzIpiAFnqjwNFia9ki+o0pAdgjb/dd5E2wUJg8LbQBqm6RrGapNg3DX+JFXVVVxPNoyA0NSJkIR",
	"3J7Kqu64Uw8CZfVL/zqkcXSNGY7hKgHfXJ27cGRkultYakJx/ys/uq77uD/ItVP7TCnclHhzdd5zKdMA",
	"tIRrZkrFj2CfkgnYFHoIN27QpPYIEVwqLivrva298W24iIs5d6w2tu68dKfwV/w8faQLeIYCi5eOoQk7",
	"eTrpus1qwecLpk3ockzIuUgVo5CZ7TyE5sZrxsIXcbsZMXcy6O4mNJgLE6J9viHG2thbljrXHa49cwze",
	"6iMYE1zE16Th6C1WqSrKwNi0Qhwm9FjTfVS7doZr8tShrUKyJqWLgmR2+RVcsF2AbsjW/vL8viJ9Rye7",
	"HWDrFOIupeJhjrJtBB2mb9T6zGdAdlyzESoSKmYUD2l4m4TRB1t+9fKJWwD2kz8XhqkVza9ZKkXWo7W4",
	"+4hMmbmzvv0ngA0PM+yGaZzdKExgAIbssKXgRlvNYfH1Gu7IC/XNelUX3qUHmsKXsvRt9tBlj5EKtDvE",
	"vVdcNCNeQc3HOyUo/ML1Qm0TtCEe9oxDVCbwPhYeitugw5qBQn/FSjNimPogECW5nBMmjFqPwN5dgVin",
	"FvNor0LmQbCEozDcJxzf2CTlo6SgM8t9qfmRiUzaFX6FgbC4YqRPabxZZtRAzUimmfGlh87WaR4evvY3",
	"C2k4iAmp1M85nQupDU+fU0OTUXLx4tXw/KDuTk78c5KFF3BsDAsfxlM68f+TFTzAG2ur0EpjdifJJZ5P",
	"i883lfCuSoMYu1lEHwty8eJVB/cGuRIhKx4Dz3in9nm9/xYhTvwjd7QQno4DOeJO7dI3ze7q5DnBJ948",
	"NFzMsQYYlBJce4PH3aYebOUzv2R2dPdOq8XmKyuAkNHEri/R7cmFwbabRKH3PU7y14d5aAuoBmnnZoLb",
	"TfiHnL+wMmv34y17ZFdU1QFq8D1WwkUc32tC8SUV4/NPxfhdJUDsEZu4UHzOxcWsJn53EwqbNvGvt27a",
	"P6hU6N6cr4aM9urcgd6H2aHvvQTSXWJ+2I36Gko/vQ35mDyn/rrdlFqDRy596MMlorTCNFKkjV7w5rhC",
	"rvyBZd+uuoytgzB/aW+875hL9JoXTBtaLHvsC140AZUplBPKas6itQ+P7McHXB61ONxGQO5HyY1m6rQ0",
	"CyskUdZcw1R7KgPhgQnrHNXaBNEabscMMEVnfkJxkxoLP4Z/fHP1D78F1AC8lkHLdSe4rUl579lJlalz",
	"JC0SwtS0t1d1mRu/O2J7im5X7DTjniJv3rhBuwkRQAoRezj3+nFgez/gHhynD5UlgXHe8CVkemdVrUHa",
	"dGHYW65NVOEwPorkYjV5rdzKJs/nk440dLhRUYjhNGcKbp6ozrlBcadwO9gOp4WgK1/TIVIdVnXZd+PW",
	"OB0f8/iDcQ2Sjq9hFwT0havf4j/eUtCngjUUlWrIddrrFMOmd9q8rwU88u4Z7j5E4L4RKSjcMEFFykZY",
	"1siueTjsDIsSI7j+aw+Pq+MTrh5jBhKeU8NXdmTB7kIApY3jwfCG3Ot+MsDeTnVFuktwdQqhK1Wb5nd0",
	"rUPKat3htMaj8gVkGtGPxlnijguUI/HhD6pEd9DdVJKwKCzt4j06rMLauMngEGJ8C1DVFmBoCmGkINq/",
	"joYb7uU0ba1IIFz8PRkl/0WVwDmdKQ73uuwQFPQtILDk/olIGJicFwXLIK+5Jmwv/p6cJD9AkftxBEo9",
	"TNUlp2vc0OeploL/WnY4rLF+iMri1itO+Ir7oabQobhgEziDuOA824P4wy7Or6nN+H7/5NCX1zV1dDzY",
	"ECTY+eyBhotNlZr70oMvXrwi7K1hcPlMhIrtxg1+0SxHZvurAqxuugEbta18uLd7Xc17W2KRWysQZPpk",
	"rZlR8q+fTo/+SY9+gyH+46tdojR4MXzDJKrXpQ3iT1gRNJv5TQEu5vAo/IOvIMN9uEy0rZBvqqJWGrcX",
	"WEbkbOYIHt0aGwmh0AZLjtjFw0UJicyQGnF68/+wLxCfYtNIwKoO+o7P4MW4MV0reQ0rllJRtXYVb/0O",
	"sbPEB88gpYIY+sa7zNLXbItK6srZLPI0IiJshMM2EjDBg8Ehqjvx+051Bkyujm+Pv3H+T63EQo25Xgjr",
	"FULxU679T7ijZbq+mM1yLlj14HpJ8ZY38Zppg8+VQS7De/qSUXIj6IpycDarDp6zGVOOH/9vyZlOYSDY",
	"RPNPaW7VDYDC5opmm7k5rgpXtd2pJms8qw3VVd3MXNfh0pvqMjS3Le6qRufrsJcOnxiWGpZtumaZVgfq",
	"125nOaAwXMQY7ll0gzav9x3XsOxy0l2NpJC25FmKijXYlHAb2bQ05NeSWWlujXArm5lGuRwI4erQRHOP",
	"F2nmPhvHbNSBr1ob9x3WChjUhInQwnHglgalyJiaSwgrMo2ldxV6dHF1Rthmo0tTutzqqrzKDCg4Ledz",
	"LubjGpfWMfxr6Yzz2tqmacqWcDcYUVTMwQKo7bKGpVDvrZorEAdqQDhYXdqrXQ5QrNGlOXhijturdxhS",
	"YSB6RzmWPLV2hBI099mTsaeGF4nVRMKWMaLz+SwrRUZFugbI4S5wNyiZUZ7LFdbyd/cfDoECBdAWCLT7",
	"btwtoLbB79azxVF1iZNXTEGItYhYujdY/NMX5yqr8VFC+MWzOTxQk0KdznA4rNMto9yl3h17U9h35UMM",
	"tFibAqcfrkOLok0j9TF3VWcar0N0/UHdpy7B1Y9iukHgBNJ2yLV9egTNkMeSA5m4LgA3s0OVE/YIMnEI",
	"E7yPlBzY/8Hl5ybixQTz5iDP17WVbgHB25FTWbBIwYe6fC2p2ydmh4IyaHhaGmkp666QjIW1F8ijDTDi",
	"1T1VCCy6fFzggZtwH4W/0LAqBxPv1zUl+WaWjqdpPcdiafxxH0WFK0ZuJJm4JTjZLPj3WZmxUrACzR/k",
	"7NMMAxnX6wznNPg3Ee0a+gOXCiMAbJBqOVuxHKoTYNgVqtdH16aCubLBjYgluzuxXJPB1rv4Dh7Gy391",
	"fOsfhiUbWnei3x1lreGqOiG9oRJ0Y1gApuXqYPG5HcvUaGgIOjsOIAfahys4FzzPFNuUiNax51+9I61d",
	"oDjiXo9A7niQqCP/7pCniKqTG/6AzYrFu3U4BTB8/CTCZDt3uoKHHLqAS+lnM5aa+nlxqfzvK5nn5XLS",
	"F6L2IXzbkZJ5TsplVbkpGkhCqgwaBm5n0fc0IqX2KQmTgMlz4YqDeCRPqqQ4n4jwPdWMuJgUuaryouCA",
	"VHXMpJbfh3N2cpOiARTDmaYlmMZUx4+pPxmzam1l9GZBHOPiqgLtHVl/yPjRXUIxn3rFbc1GTAvgcOZ2",
	"yURWMyT3yK4MqRaHS6uss2t7aqweZ5clBLQ0zxgaPz1zi+K/uhEABiUodasqQH/oN+bpbpJYTWzHqMEf",
	"OK66kqJxV90nhX4vWh8U3YS8tMsoKIUK3jgsPSKasY5yT9WGW3OU59RQAgVmD5PEt+GCsk7s7UHtw99H",
	"VjNresC8v3/P8hRi7ZW0VJ6homPUNXX9SSdLuDzGKynNbfR7n1s8o+aTavPYH6UGAklpmh5/2BX395Q4",
	"+/vrJwq/eLI6/prcXJ2PCTnNcxe3iS44adcfj7sPlcfDhUrOObBqzd3CGWqZg6MR/guSL1QkkdJ8Lpdz",
	"nmHN092zdj+BWz2hLObuM9urZrXjs43F1Ws11VlnNRUUHslJ8q+ff87+4+efx9Gfrw6YwVnXlJFMMDKV",
	"uYcU0stdOnIUxLtsfDYoiDeyutOVcYIsPLeYnGbFs8Z4z9AeNLu5OX/eUQKuM9+BhrGjm5n+a8EEub5+",
	"fukPTdduEK3l+sA5AzugK02EmKGC/O3160syefb0Kbn4+6SKU6Ct73qfvDq6fnF6dfa3iY85kgwjXxnX",
	"qbW81l1JlBFj/PT06Dt6NDs9evnLu7/cH8X/frvLv8fP7r96oJT5COHdvB5j/nzWj/eOqlsPjXxCrl6e",
	"fXv87FmkswpmFjKDRPMSA0+pYpgUBqAAsI0sDZ9j6u17PAY6ZUQu6a/w9RlmpvuCu74NxBCN7R8rHDtj",
	"HPuFbLtScLvyIIzWTumBasvYlZAGFd9SwRbImuhyOuMsz2phUTuH8Ycrhr/FIvikzaqWmu9UDBdg0Dey",
	"4agvfPMAdUw8m3o3rn1I22VOW5gxtz0uGKQbvlSaSuWLIMFcjoKKQG50nToCgyfV40Dplj/TuFhqSxEG",
	"vNsd9l3qF3K1yg3sWVJgO+qoIK6T+l2sZgig8YT9TTb910a/eE3nXc7ZQ3FFKAvmDzM0LikBeEASLxjN",
	"IAIf+7BXL8/+17NvntVnyXdKVqy7Wx9kWfRlUbaiC4difLRydj3WHNCB1Z5jtHU6Lju6HffDi39tQ2o4",
	"hhFA1k2YY3TEN8m12ebm6tzvDEVXp4EBERahFWq+pDJVhtPcX4j3QZiKeqDjgHDIcASLJ1LAo52mEyPO",
	"bD2sTh9JikCJLEXnBep/aoKXoTuL8hxqUVmu5a4kZYrFF+xPPAWVPH/1+mUySkqVJyfJwpilPnny5O7u",
	"bpwVZjaWav7EGq0ZVZn2QQmL3w6roeYvRDIQUNxh3xhuoPqCe5WMkpV3JJNnT5/9afwNoDuVy7Xi84WB",
	"3R33m9gPiIV9DOFGTMvIc3hEQhOylDlP1xhstJNrzg0ueHoCX3Gmn1RjWRZaMkGXPDlJvhk/HR+jp7oA",
	"6RGFZ57Y/+cMUBq21a3jnvwnM95BPgbGcqcY7JfPnj715GCo3125Wtv6yX9r9KZRBm2TUH1RLCB8m+2D",
	"lxDoRXvK4UedBYZE2sPRl4NNoFb9tQNqeFHtythP7kc1GnxVMEMzKEUygBiv/Mc7EeVtkScn79rQoR0b",
	"IBh/nBiKQl5b8eO/fUCedUNE9wq3nrw//7a6/Mi52MH75J37cZ7d70Kv0OoRCOfJdTAifWykscK+Kln6",
	"U2dks9L4jJxnlc7vm5lVw8kJaJFk5PVvnWo+EoG2RzW7RjkTyC6IWScO/G6Xf/7jB+STIReHvzfvtLr8",
	"yBe4R/yTd+7X0BXuG4Zmj0C6cPHwocj0GS7x1sw6l3idavsu8WibYCu/+G8fUhG4CxVxqFiR97w4gKro",
	"6fkjX/WOGE/e1eEfuvZd82bjx6Ntg6KHpuPnqPl7JthtAHQRdriQuL///wEAAP//35Jb6O3OAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
